### ISSUE TITLE
some way to use `feross/standard`?

### ISSUE THREAD

**Issue by tunnckoCore** [wooorm/eslint-md#1]
actually [eslint-standard-config](https://github.com/feross/eslint-config-standard) which is used in `standard` - it is not a json, it is not a plugin... hm. 

/cc @wooorm @feross @maxogden Ideas?

**Comment by feross** [comment]
No idea what you're asking for, but we could include the `esltin-standard-config` rules in a JSON file if that would make your life easier.

**Comment by wooorm** [comment]
Oh interesting, I actually re-created eslint-md as an eslint plugin, but didn't publish yet because eslint didn't have the possibility to test plug-ins.

Anyway, that might’ve been [fixed](https://github.com/eslint/eslint/issues/1971), but I haven't checked since.

Have you checked using eslint-md with eslint-standard-config, just like you would with eslint?

**Comment by tunnckoCore** [comment]
@feross yea I thought to suggest that, it would help, yea.

> Have you checked using eslint-md with eslint-standard-config, just like you would with eslint?

nope, I just use `standard` cli.

Hm... have idea. Maybe opposite would be cool. `standard` to support some flag to validate markdown files. /cc @feross ? You can use [jonschlinkert/gfm-code-blocks](https://github.com/jonschlinkert/gfm-code-blocks) to extract code blocks, if that help.

Or it can be implemented here and `standard` to use `eslint-md` when flag is present. opinions?

**Comment by tunnckoCore** [comment]
doh.. nope. it won't help. should create package that extract gfm-code-blocks then check/format them and rewrite them in same place [then write to file] lol.

**Comment by wooorm** [comment]
@tunnckoCore Re “nope, I just use standard cli”, well that would probably be called standard-md then, right haha?

Also: You don't just need to extract the code blocks, you need to change the positional information on lint warnings too. There’s also some ambiguity with the fact that multiple code blocks should be linted as a single javascript file.

P.S. can standard rewrite JavaScript?

**Comment by tunnckoCore** [comment]
@wooorm actually I got idea, we can close that for the moment.

> can standard rewrite JavaScript?

actually, i can say "partially yea". standard-format have method `.transform` and I made it locally to do the things only when `--format` option is given to standard - it just works, but as i said have some better and bigger idea.

**Comment by wooorm** [comment]
What, you want me to close this issue?

**Comment by wooorm** [comment]
Alright, let me know if you need my help in the future!

**Comment by tunnckoCore** [comment]
@wooorm yea, thanks!

I will ping all of you soon.
