### ISSUE TITLE
Can you confirm this works with extends in node v4.2.1?

### ISSUE THREAD

**Issue by gaboesquivel** [wooorm/eslint-md#2]
Hi @wooorm, I'm trying you use you module to lint a javascript book we're starting to write at @costaricajs. We want to use [airbnb's style guide](https://github.com/airbnb/javascript) however eslint-md doesn't seem to read from extends, here's the [code](https://github.com/gaboesquivel/Fundamentos-de-JavaScript/tree/linting-markdown) ... if you `npm test` you can see it doesn't read from airbnb/base, you can notice it as it complains about qoutes not being double while airbnb/base specifies single qoutes.
I would appreciate any insight on this. thanks

**Comment by wooorm** [comment]
Hey @gaboesquivel! Sorry but I don’t quite understand what you’re asking. Could you be more clear?

Do keep in mind that eslint-md is hardly maintained (I have a lot of things to work on which I’m bit more interested in, sorry)

**Comment by gaboesquivel** [comment]
Thanks @wooorm. It seems that eslint-md doesn't support [extends](http://eslint.org/docs/user-guide/configuring.html#extending-configuration-files), perhaps eslint needs to be updated. At the end I decided to eslint-plugin-markdown instead.
