### ISSUE TITLE
Refactor as ESLint preprocessor

### ISSUE THREAD

**Issue by mik01aj** [wooorm/eslint-md#3]
Since https://github.com/eslint/eslint/issues/1817 is now closed, could this module be refactored to be a preprocessor for `eslint`?

**Comment by wooorm** [comment]
Certainly, and that would be very awesome! I, however don’t have the resources to work on this :(

**Comment by wooorm** [comment]
I just saw https://github.com/eslint/eslint-plugin-markdown, making this project obsolete. I’ll post a deprecation notice here, and suggest using **eslint-plugin-markdown**.

**Comment by mik01aj** [comment]
:+1:
